// This file configures Firebase SDK options. Auto-generated by FlutterFire CLI.
// DO NOT edit this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:android:aaaaaaaaaaaaaaaa',
    messagingSenderId: '000000000000',
    projectId: 'shougaku-kore-doutoku',
    databaseURL: 'https://shougaku-kore-doutoku.firebaseio.com',
    storageBucket: 'shougaku-kore-doutoku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:ios:bbbbbbbbbbbbbbbb',
    messagingSenderId: '000000000000',
    projectId: 'shougaku-kore-doutoku',
    databaseURL: 'https://shougaku-kore-doutoku.firebaseio.com',
    storageBucket: 'shougaku-kore-doutoku.appspot.com',
    iosClientId: 'xxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'jp.petitworks.shougakuKoreDoutoku',
  );
}

// TODO: Replace the above placeholders with actual Firebase credentials
import 'dart:io';
const defaultTargetPlatform = TargetPlatform.android;
